### ISSUE TITLE
Question Answering Yaml Error

### ISSUE THREAD

**Issue by mjseithe** [HPEEzmeral/ezua-tutorials#123]
### Description & Reproduction

This block of code in the vectorstore-isvc.yaml in notebook 2 causes the service not to deploy: 
 # - name: HTTP_PROXY
      #   value: <yout http proxy URL>
      # - name: HTTPS_PROXY
      #   value: <yout https proxy URL>
      # - name: NO_PROXY
      #   value: .local

I get that it all looks like it is just commented out, but it says that it found map when it was expecting string. Removing that block makes it run as expected.

### Expected behavior

The service deploys when i run the kubectl apply

### System Info

ezaf version: 1.2.0.  noteboook image: data science q4

**Comment by AlexanderOllman** [comment]
This has been added for HPE internal hosting. It can be rectified by declaring variables and parsing in defaults if none are given. 

Keeping this issue open until a PR resolves.

**Comment by dpoulopoulos** [comment]
The `env:` line shouldn't be commented out. The easier fix is to move this line up and uncomment it.
